Add reloading icon
digital-taco/react-draft pull request #42
Opened 2019-11-24 04:12 UTC by zachintosh

Adds:

- A reloading icon at the bottom left whenever HMR kicks in to reload the page

2019-11-24 04:39 UTC, kyle-west requested changes
Minor thing. Also do you have a screenshot of the thing in action?

2019-11-24 04:39 UTC, kyle-west commented on src/components/ActivityBar.js
> +  // hi
Was this left over from testing HMR?

2019-11-25 14:34 UTC, zachintosh commented on src/components/ActivityBar.js
> +  // hi
Yup, I just removed it

2019-11-25 19:58 UTC, kyle-west approved these changes

2019-11-25 19:59 UTC, merged